var RES={
		
	"EMAILWRONG":"E-Mail Format ist nicht korrekt",
	"EMAILEXIST":"Testen Sie, ob das Konto verfügbar ist",
	"EMAILHASEXIST":"Das Konto ist nicht verfügbar",
	"EMAILRIGHT":"Das Konto ist  verfügbar",
	"PWDLENGTH":"Die Länge des Passworts sollte mehr als 6 Zeichen betragens",
	"PWDNOOK":"Das Passwort muss alphanumerisch sein",
	"REPWDWRONG":"Die Passwortbestätigung ist erforderlich",
	"RES_QUESTION":"Der Frage darf  nicht  leer sein",
	"RES_ANSWER":"Der Antwort darf nicht leer sein ",
	"FIRSTNAMEWORNG":"Familienname darf nicht leer sein",
	"SNAMEWORNG":"Vorname darf  nicht leer sein",
	"PASSWORDNOTNULL":"Passwort dar nicht leer sein",
	"REQUESTWRONG":"Anfrage fehlgeschlagen",
	"LOGINFALSE":"E-Mail oder Passwort ist nicht korrekt",
	"LOGINFALSE1":"Die E-Mail, die Sie angegeben haben, ist nicht korrekt",
	"LOGINFALSE2":"Das Passwort, das Sie angegeben haben, ist nicht korrekt ",
	"LOGINFALSE3":"Anzahl erlaubter Versuche überschritten",
	"LOGINFALSE4":"Der Sicherheitscode, den Sie angegeben haben, ist nicht richtig",
	"BUILDING":"Projekt ist im Aufbau",
	"INPUTISNO":"Bitte geben Sie PMU Seriennummer ein",
	"INPUTREGISTCODE":"Bitte geben Sie den Registrierungsschlüssel ein",
	"PSNOCANNOTNULL":"PMU Seriennummer darf nicht leer sein",
	"PSNORIGHT":"Die PMU Seriennummer ist verfügbar",
	"PMUNOTEXIST":"Die PMU Seriennummer exisiert nicht",
	"PMUHASBINDED":"Die PMU wurde verbunden",
	"PMUCHECKCODEERR":"Registrierungsschlüssel  ist falsch",
	"ONLYNUM":"Nur Zahlen und Dezimalpunkte sind erlaubt.",
	"CO2XSCANNOTNULL":" CO2 vermeiden Koeffizient darf nicht leer sein",
	"GAINXSCANNOTNULL":"Gewinnskoeffizient  darf nicht leer sein",
	"STATIONNAMENOTNULL":"Kraftwerksname darf nicht leer sein",
	"STARTDTSTYLE":"Datum der Inbetriebnahme: Format (yyyy-mm-dd)",
	"STARTDTSTYLEERR":"Datum der Inbetriebnahme: Format (yyyy-mm-dd) ist falsch",
	"INSTALLCAPERR":"Installierte Leistung muss numerisch sein",
	"EVENTDELSUC":"Löschen Sie die Ereignis erfolgreich.",
	"EVENTDELERROR":"Löschen Sie die Ereignis fehlschlagen",
	"STATIONNAMENOTNULL":"Kraftwerksname darf nicht leer sein",
	"XMUSTNUM":"Längengrad muss numerisch sein",
	"YMUSTNUM":"Breitengrad muss numerisch sein",
	"HMUSTNUM":"Geben Sie die Höhenzahl ein (numerisch)",
	"AZMUSTNUM":"Bitte geben sie den Richtungswinkel ein (numerisch)",
	"AOIMUSTNUM":"Fallwinkel muss numerisch sein",
	"AOIMUSTNUM_INSANGLE":"Fallwinkel sollte kleiner als 360 sein!",
	"CO2XSMUSTNUM":"CO2-Vermeidung  muss numerisch sein",
	"GAINXSMUSTNUM":"Gewinn muss numerisch sein",
	"SNAMENOTNULL":"Kraftwerksname darf nicht leer sein",
	"SNAMEINPUT":"geben Sie den Kraftwerksname ein",
	"COUNTRYSELECT":"Bitte wählen Sie ein Land aus",
	"XMUSTINPUT":"Längengrad eingeben",
	"YMUSTINPUT":"Breitengrad eingeben ",
	"STATESELECT":"Stadt / Provinz wählen",
	"REGNOINPUT":" Registschlüssel  darf nicht leer sein",
	"CITYINPUT":"Stadt eingeben",
	"CO2XSNOTNULL":"CO2 vermeiden Koeffizient darf nicht leer sein",
	"GAINXSNOTNULL":"Gewinn Koeffizient darf nicht leer sein",
	"SUREDELSTATION":"Sind Sie sicher, dass Sie dieses Kraftwerk löschen möchten?",
	"SUREDELPMU":"sind Sie sicher, dass Sie diesen Monitor löschen wollen?",
	"VSPASS":"Verifikation durchgeführt",
	"VSWAIT":"PMU Verifikation ist nicht bestanden, bitte warten",
	"PMUIDEXWRONG":" Registrierungsschlüssel ist falsch",
	"DELSTATIONERR":"Entfernen des Kraftwerks fehlgeschlagen",
	"DELSTATIONERR_HAVEPMU":"Verwijder installatie mislukt: Verwijder de monitor.",
	"ONLYCANC5USERS":"Sie können nur 4 Benutzer erstellen",
	"SUREDELNUSER":"Sind Sie sicher, dass dieser Benutzer zu löschen",
	"EMAILTIP":"Bitte geben Sie Ihre E -Mail-Überprüfung , um die Registrierung abzuschließen",
	"PWDTIP":"Muss aus 6-16 Buchstaben oder Zahlen bestehen",
	"REPWDTIP":"Passwort bestätigen und das Passwort müssen konsistent sein",
	"FNAMETIP":"Familienname darf nicht leer sein",
	"LNAMETIP":"Vorname darf  nicht leer sein",
	"STANAMETIP":"Kraftwerksname darf nicht leer sein",
	"CO2RATETIP":"CO2 Veimeiden Koeffizient muss numerisch sein",
	"CURRENCYTIP":"bitte wählen Sie die Währung",
	"INCOMERATETIPTIP":"Gewinn Koeffizient muss numerisch sein",
	"PZINV":"Einstellungen des Wechselrichters",
	"CKINV":"Aktuelle Einstellungen betrachten",
	"BACKINV":"zurück zur Konfiguration Inverter",
	"BACKINVTIP":"Sie haben nicht die Inverter gewählt, Bitte zurück zur Konfiguration Inverter",
	"PZINVOK":"Okay",
	"PZINVCANNEL":"Abbrechen",
	"CHOOSEMONEY":"bitte wählen Sie die Währung",
	"CHOOSETIMEZONE":"bitte wählen Sie die Zeitzone",
	"ADDPMU":"PMU hinzufügen",
	
	/** 2013-06-21 --PMU SN. To SN. **/
	"PSNO":"SN.",
	"BYNAME":"neue Deckname",
	"OLDBYNAME":"alte Deckname",
	"ATTR":"Eigenschaft",
	"FACTORY":"Fabrik",
	"SOFTVRE":"Software version",
	"HARDVRE":"Hardware version",
	"LTIME":"Zuletzt aktualisiert",
	"USEDSPACE":"belegter Speicherplatz",
	"TOTALSPACE":"Gesamtspeicherplatz",
	"DELETESYSUSER":"Sind Sie sicher, dass Sie diesen System-Administrator löschen wollen?",
	"CHART_CHART":"Grafik",
	"CHART_IDC":"DC Strom",
	"CHART_VDC":"DC Volt",
	"CHART_ENERGY":"",
	"CHART_FAC":"AC Frequenz",
	"CHART_IAC":"AC Strom",
	"CHART_VAC":"AC Spannung",
	"CHART_TMPE":"Wechselrichter Temperatur",
	"CHART_GAIN":"Gewinn",
	"CHART_CO2":"CO2 Vermeiden",
	"CHART_UPDATEUSERINVT":"Änderung des Wechselrichters erfolgreich!",
	"CHART_UPDATEUSERINVT_MAX":"Sie können maximal 5 verschiedene Wechselrichter wählen, bitte wählen sie noch einmal!",
	"CONF_INPUT_BYNAME":"bitte geben Sie den Benutzernamen ein",
	"CONF_INPUT_BYNAME_FORMAT":"Bitte geben Sie den rechtlichen Charakter!",
	"CONF_INPUT_PSNO":"Bitte geben Sie PMU Seriennummer ein",
	"CONF_INPUT_SERIALNO":"Bitte geben Sie den Registrierungsschlüssel ein",
	"CONF_ADDPUM_SUCCESS":"Hinzufügen erfolgreich!",
	"CONF_ADDPUM_ERR_NODIFINE":"Hinzufügen fehlgeschlagen: Unbekannter Fehler",
	"CONF_ADDPUM_ERR_PSNOERR":"Hinzufügen fehlgeschlagen: PUM Seriennummer fehlerhaft",
	"CONF_ADDPUM_ERR_PSNUSED":"Hinzufügen fehlgeschlagen: PUM Seriennummer  wurde bereits verwendet",
	"CONF_ADDPUM_ERR_NOSTATION":"Hinzufügen fehlgeschlagen: Unbekannte Kraftwerksnummer oder Seriennummer",
	"CONF_INPUT_PSNODEL":"Bitte geben Sie PMU Seriennummer ein",
	"CONF_DELPUM_SUCCESS":"erfolgreich löschen",
	"CONF_DELPUM_ERR_NODIFINE":"Löschen fehlgeschlagen: Unbekannter Fehler",
	"CONF_SET":"Einstellung",
	"CONF_DOWNDATA":"Daten laden",
	"CREATEDT":"Erstellungsdatum",
	"DEVNAME":"Gerätename",
	"FACTORYNAME":"Hersteller",
	"PENPAI":"Marker",
	"SOFTVER":"Software version ",
	"HARDVER":"Hardware version ",
	"E_TOTAL":"Gesamtkapazität",
	"E_TOTAL_EX":"E-Total(Initial)",
	"H_TOTAL":"Gesamtstunde",
	"DEVMODELNAME":"Typ",
	"DEVTYPENAME":"Modell",
	"SET_SUCCESS":"Setup erfolgreich",
	"SET_FAILD":"Setup fehlgeschlagen!",
	"NEED_NUMBER":"Bitte geben Sie eine ganze Zahl ein",
	"INPUT_TOOLARGE":"Der eingegebene Wert ist zu groß",
	"PMU_USEDSPACE":"Speicherplatz",
	"PMU_TOTALSPACE":"Gesamt- Speicherplatz",
	"PMU_STATE":"Zustand",
	"PMU_SOFTVER":"Software version",
	"PMU_HARDWVER":"Hardware version",
	"PMU_LLIP":"Letzte Login IP",
	"PMU_CURGATE":"Last Login DCGate",
	"PMU_LLDT":"Letzter Login Zeitpunkt",
	"RES_DATA_LIST_T":"Zeit",
	"RES_DATA_LIST_D":"Termin",
	"RES_DATA_LIST_M":"Monat",
	"RES_DATA_LIST_Y":"Jahr",
	"RES_DATA_LIST":"Numerische Tabelle",
	"RES_DATA_LIST_W":"Leistung ",
	"RES_DATA_LIST_ENERGY":"Energie",
	"RES_DATA_LIST_POWER":"Pac",
	"RES_FIND_PWD_MAILSEND":"System Bestätigungs-Code an Ihre Mailbox geschickt , nach der Lesen entnehmen Sie bitte  Bestätigungs-Code  um Ihr Passwort zu ändern",
	"RES_FIND_PWD_MAILFAILD_ACC":"Validation Code für Versagen,  Ihr Konto ist nicht existiert!",
	"RES_FIND_PWD_CHECKCODE_ERR":"System Bestätigungs-Code falsch, versuchen Sie es erneut oder wenden Sie sich an Ihren Systemadministrator !",
	"RES_FIND_PWD_INOUT_CHECKCODE":"Bitte geben Sie den Registrierungsschlüssel ein",
	"RES_FIND_PWD_INPUT_NEWPWD":"Bitte geben Sie das neue Passwort",
	"RES_FIND_PWD_REPWD":"Bitte  bestätigen Sie das neue Passwort",
	"RES_FIND_PWD_TWO_PWD":"Die beiden Passwörter sind inkonsistent",
	"RES_FIND_PWD_UPDATE_OK":"Passwort erfolgreich geändert, wollen Sie auf die Login- Seite zurückzukehren ?",
	"RES_FIND_PWD_ERR_CHECKCODE":"System Bestätigungs-Code ist falsch !",
	"RES_FIND_PWD_ERR_ACC_NOTFIND":"Das Konto existiert nicht, Änderung fehlgeschlagen!",
	"RES_DOWNLOAD_TYPE_TXT":"TXT",
	"RES_DOWNLOAD_TYPE_CSV":"CSV",
	"RES_ACCOUNT":"Konto",
	"RES_ACCOUNT_STYLE":"Konto Format",
	"RES_ADDSHAREACCOUNT":"Gemeinsamen Benutzer hinzufügen",
	"RES_ADDSHAREACCOUNT_NEEDINPUT":"bitte geben Sie ein gemeinsames Konto an",
	"RES_ADDSHAREACCOUNT_ERR_UNKOW":"unbekannter Fehler",
	"RES_ADDSHAREACCOUNT_ERR_NOACC":"Das Konto existiert nicht",
	"RES_ADDSHAREACCOUNT_ERR_HAVESHARE":"Dieses Konto ist ein gemeinsames Konto",
	"RES_DELSHAREACCOUNT_ERR":"Löschen fehlgeschlagen",
	"RES_DELSHAREACCOUNT_CONFIRM":"Sind Sie sicher, dass Sie dieses gemeinsame Konto löschen wollen?",
	"RES_SHAREACCOUNT_UNLOCK_OK":"Entsperren Erfolg",
	"RES_SHAREACCOUNT_UNLOCK_FAILD":"Entsperren fehlgeschlagen",
	"RES_SHAREACCOUNT_LOCK_OK":"Erfolgreich gesperrt",
	"RES_SHAREACCOUNT_LOCK_FAILD":"Sperren fehlgeschlagen",
	"RES_REPORT_EVENT_DATE_ERR1":"Die gewählten Zeiten sind nicht gültig",
	"RES_REPORT_EVENT_DATE_ERR2":"Das Zeitintervall ist zu lang , und  Zeitintervall nicht mehr als 7 Tage sein!",
	"RES_PLANT_JD_ERR1":"Grad des Längengrads sollte kleiner als 180 sein!",
	"RES_PLANT_JD_ERR2":"Minute des Längengrads sollte kleiner als 60 sein!",
	"RES_PLANT_JD_ERR3":"Sekunde des Längengrads sollte kleiner als 60 sein!",
	"RES_PLANT_JD_TOTAL":"Longitude should be less than 180!",
	"RES_PLANT_WD_ERR1":"Grad des Breitengrads sollte kleiner als 180 sein!",
	"RES_PLANT_WD_ERR2":"Minute des Breitengrads sollte kleiner als 60 sein!",
	"RES_PLANT_WD_ERR3":"Sekunde des Breitengrads sollte kleiner als 60 sein!",
	"RES_PLANT_WD_TOTAL":"Latitude should be less than 180!",
	"RES_POWER_DOWN_DALIY":"Erzeugungskapazität",
	"RES_POWER_DOWN_D":"Tag",
	"RES_POWER_DOWN_M":"Monat",
	"RES_POWER_DOWN_Y":"Jahr",
	"RES_POWER_DOWN_T":"Total ",
	"RES_CHART_DOWN_ISNO":"Seriennummer",
	"RES_CHART_DOWN_TIME":"Zeit",
	"RES_CHART_DOWN_TEMP":"Temperatur",
	"RES_CHART_DOWN_OBJ_1001":"CO2 vermeiden -Tag",
	"RES_CHART_DOWN_OBJ_1002":"CO2 vermeiden -Monat",
	"RES_CHART_DOWN_OBJ_1003":"CO2 vermeiden - Jahr",
	"RES_CHART_DOWN_OBJ_1004":"CO2 vermeiden - Total",
	"RES_CHART_DOWN_OBJ_1101":"Gewinn-Tag",
	"RES_CHART_DOWN_OBJ_1102":"Gewinn-Monat",
	"RES_CHART_DOWN_OBJ_1103":"Gewinn-Jahr",
	"RES_CHART_DOWN_OBJ_1104":"Gewinn-Total",
	"RES_CHART_DOWN_OBJ_1201":"DC Strom-Tag",
	"RES_CHART_DOWN_OBJ_1202":"DC Strom- 7 Tage",
	"RES_CHART_DOWN_OBJ_1301":"DC Volt-Tag",
	"RES_CHART_DOWN_OBJ_1302":"DC Volt- 7 Tage",
	"RES_CHART_DOWN_OBJ_1401":"AC Frequenz -Tag",
	"RES_CHART_DOWN_OBJ_1402":"AC Frequenz- 7 Tage",
	"RES_CHART_DOWN_OBJ_1501":"AC Strom-Tag",
	"RES_CHART_DOWN_OBJ_1502":"AC Strom- 7 Tage",
	"RES_CHART_DOWN_OBJ_1601":"AC Volt-Tag",
	"RES_CHART_DOWN_OBJ_1602":"AC Volt- 7 Tage",
	"RES_CHART_DOWN_OBJ_1701":"Wechselrichter Temperatur-Tag",
	"RES_CHART_DOWN_OBJ_1702":"Wechselrichter Temperatur- 7 Tage",
	"RES_CHART_DOWN_OBJ_1801":"Leistung- Tag",
	"RES_CHART_DOWN_OBJ_1802":"Leistung-  7 Tage",
	"RES_CHART_DOWN_OBJ_1803":"Leistung- Jahr",
	"RES_CHART_DOWN_OBJ_1804":"Leistung- Total",
	"RES_CHART_DOWN_CO2":"Reduzierung",
	"RES_CHART_DOWN_YIELD":"Gewinn",
	"RES_CHART_DOWN_POWER":"Leistung",
	"RES_CHART_DOWN_ENERGY":"Energie",
	"RES_CHANGEPASSWD_INOLDPWD":"Geben Sie das Original-Passwort ein",
	"RES_CHANGEPASSWD_INNEWPWD":"Geben sie das neue Passwort ein, Länge zwischen 6 und 18 Zeichen",
	"RES_CHANGEPASSWD_INCOFMNEWPWD":"Bitte bestätigen sie das Passwort",
	"RES_CHANGEPASSWD_INCONFMPWDERR":"Die beiden eingegebenen Passwörter stimmen nicht überein",
	"RES_CHANGEPASSWD_OPT_SUCCESS":"Passwort erfolgreich geändert !",
	"RES_CHANGEPASSWD_OPT_FAILD1":"Passwort ändern fehlgeschlagen: Das alte Passwort ist nicht korrekt!",
	"RES_CHANGEPASSWD_OPT_FAILD2":"Passwort ändern fehlgeschlagen: Das Konto existiert nicht",
	"RES_CHANGEPASSWD_OPT_FAILD3":"Passwort ändern fehlgeschlagen",
	"RES_WAP_LIKE_ALERT":"WAP-Zugang, nutzen Sie bitte die folgende Adresse in Ihren Handy-Browser",
	"RES_FIND_PASSWD_NOACC":"Konto existiert nicht oder ist nicht aktiviert, die Aktion ist  fehlgeschlagen!",
	"RES_FIND_PASSWD_ERRCODE":"Bestätigungs-Code ist falsch !",
	"RES_FIND_PASSWD_IMGNUM":"Geben Sie die Zahlen aus dem Bild ein",
	"RES_FIND_PASSWD_INCODE":"Geben Sie den Bestätigungs-Code ein!",
	"RES_FIND_PASSWD_CODENUM":"System Bestätigungs-Code muss ein vierstellige Zahl sein",
	"RES_CONFIG_REPORT_SEND_OK":"Bericht wurde erfolgreich versendet!",
	"RES_CONFIG_REPORT_SEND_ERR":"Bericht versenden fehlgeschlagen.",
	"RES_CONFIG_REPORT_SEND_MAIL":"Bitte geben Sie eine E -Mail-Adresse ein!",
	"RES_CONFIG_REPORT_SEND_MAILEX":"Please input legal E-mail address, seperate with semicolon (;) if more than one E-mail !",
	"RES_CONFIG_REPORT_SAVE_OK":"Erfolgreich gespeichert!",
	"RES_CONFIG_REPORT_SAVE_ERR":"Speichern fehlgeschlagen!",
	"RES_CONFIG_REPORT_IN_TIMESPLIT":"Bitte geben Sie das zu sendende Intervall ein!",
	"RES_CONFIG_REPORT_IN_MAXLIMIT_ERR":"Die maximale Anzahl der Ereignisse in einem Bericht sollte zwischen 5 und 1000 liegen",
	"RES_CONFIG_REPORT_IN_NEEDTYPE_ERR":"Auswahl der Ereignisart erforderlich",
	"RES_CONFIG_DEV_INVERTER":"Wechselrichter",
	"RES_CONFIG_DEV_MONITOR":"Monitor",
	"RES_INDEX_ERR_TIME":"Ihr Computer und Server Zeitdifferenz ist zu viel, einige Funktionen ist möglicherweise nicht verfügbar , ändern Sie bitte Ihren Computer zum gegenwärtigen Zeitpunkt",
	"RES_REGIST_REMAIL":"Stellen Sie sicher, dass die Nachricht erfolgreich an Ihre Mailbox gesendet wurde",
	"RES_REGIST_MAIL_ERR":"Senden der Bestätigungs E-Mail fehlgeschlagen!",
	"RES_ACCEPT_SHAREPLAT_OK":"Teilen des Benutzerkontos erfolgreich!",
	"RES_ACCEPT_SHAREPLAT_CONFIRM":"Sind Sie sicher, dass Sie das Benitzrekonto teilen möchten?",
	"RES_REFUSE_SHAREPLAT_CONFIRM":"Wollen Sie das Teilen einer gemeinsamen Anlage abbrechen?",
	"RES_ACCEPT_SHAREPLAT_ERR1":"Der Vorgang, das Benutzerkonto zu teilen, wurde abgebrochen.",
	"RES_ACCEPT_SHAREPLAT_ERR2":"Anteil Kraftwerk Niederlage akzeptieren ! \n akzeptierende Zustände ist nicht richtig",
	"RES_REFUSE_SHAREPLAT_OK":"Die gemeinsame Anlage brechen erfolgreich ab!",
	"RES_REFUSE_SHAREPLAT_ERR1":"Gemeinsamer Kraftwerks verweigert die Niederlage zu akzeptieren ! \n Kraftwerk ID ist falsch",
	"RES_REFUSE_SHAREPLAT_ERR2":"Gemeinsame Kraftwerks verweigert die Niederlage zu akzeptieren ! \n  der akzeptierende Zustand ist nicht korrekt",
	"CONF_DELPUM_ERR_PSNOERR":"Register code or SN. ist falsch!",
	"Test":"test",
	"CONF_INPUT_LEGAL":"Bitte geben Sie sinnvolle Zahlen ein!",
	"CONF_DELETE_INV":"Wollen sie den Wechselrichter wirklich entfernen? \n Diese Aktion ist nicht mehr rückgängig zu machen!",
	"CONF_INPUT_DATE":"Start date can not be greater than the end date!",
	"CONF_ART_OK":"OK",
	"CONF_ART_CANCEL":"Cancel"
}
