var RES = {
	
	"EMAILWRONG":"Email format is not correct",
	"EMAILEXIST":"Test whether the account is available",
	"EMAILHASEXIST":"The account is not available",
	"EMAILRIGHT":"The account is available",
	//"PWDLENGTH":"The length of password should be more than 6",
	"PWDLENGTH":"Enter new password,length between 6-18",
	"PWDNOOK":"Password must be alphanumeric",
	"REPWDWRONG":"Confirm password can not be empty",
	"RES_QUESTION":"The question can not be empty",
	"RES_ANSWER":"The answer can not be empty",
	"FIRSTNAMEWORNG":"First name can not be empty",
	"SNAMEWORNG":"Last name can not be empty",
	"PASSWORDNOTNULL":"Password can not  be empty",
	"REQUESTWRONG":"Request wrong",
	"LOGINFALSE":"Email or password is not correct",
	"LOGINFALSE1":"EMAIL you entered is incorrect",
	"LOGINFALSE2":"The password you entered is incorrect.",
	"LOGINFALSE3":"Retry　time limited!",
	"LOGINFALSE4":"Verification code you entered is incorrect.",
	"BUILDING":"Project is building",
	
	/** 2013-06-21 --PMU SN. To SN. **/
	"INPUTISNO":"Please enter the SN.",
	"INPUTREGISTCODE":"Please enter the registry key.",
	
	/** 2013-06-21 --PMU SN. To SN. **/
	"PSNOCANNOTNULL":"The SN. can not be empty",
	
	/** 2013-06-21 --PMU SN. To SN. **/
	"PSNORIGHT":"The SN. available ",
	
	/** 2013-06-21 --PMU SN. To SN. **/
	"PMUNOTEXIST":"The SN. does not exist. ",
	"PMUHASBINDED":"The PMU has been Binded.",
	"PMUCHECKCODEERR":"Registry key error ",
	"ONLYNUM":"Only numbers and decimal points allows.",
	"CO2XSCANNOTNULL":"CO2 avoided factor can not be empty.",
	"GAINXSCANNOTNULL":"Yield factor can not be empty",
	"STATIONNAMENOTNULL":"Plant name can not be empty",
	"STARTDTSTYLE":"The commissioning format(yyyy-mm-dd)",
	"STARTDTSTYLEERR":"Commissioning format(yyyy-mm-dd) ",
	"INSTALLCAPERR":"Installed capacity must be numeric",
	"EVENTDELSUC":"Delete the event successful.",
	"EVENTDELERROR":"Delete events failed.",
	"STATIONNAMENOTNULL":" Plant name can not be empty",
	"XMUSTNUM":"Longitude must be numeric",
	"YMUSTNUM":"Latitude must be numeric",
	"HMUSTNUM":"Please enter the altitude and must be numeric",
	"AZMUSTNUM":"Please enter the azimuth must be a number ",
	"AOIMUSTNUM":"Angle of inclination must be numeric",
	"AOIMUSTNUM_INSANGLE":"Angle of inclination should be less than 360!",
	"CO2XSMUSTNUM":"Of CO2 emission reductions must be digital",
	"GAINXSMUSTNUM":"The income must be a number",
	"SNAMENOTNULL":"Plant name can not be empty",
	"SNAMEINPUT":"Enter plant name",
	"COUNTRYSELECT":"Please select a country.",
	"XMUSTINPUT":"Please enter the Longitude",
	"YMUSTINPUT":"Please enter the latitude. ",
	"STATESELECT":"Please select State / Province",
	"REGNOINPUT":"Registry key must be filled.",
	"CITYINPUT":"Please enter a city",
	"CO2XSNOTNULL":" CO2 emission reduction factor must fill out the ",
	"GAINXSNOTNULL":"The income coefficient can not be empty",
	"SUREDELSTATION":"Are you sure to delete this PV Plant",
	"SUREDELPMU":"Are you sure you want to delete this monitor?",
	"VSPASS":"Verification passed",
	"VSWAIT":"PMU verification not passed,please wait.",
	"PMUIDEXWRONG":"Registry key error.",
	"DELSTATIONERR":"Remove plant failed",
	"DELSTATIONERR_HAVEPMU":"Delete plant failed: Please remove the monitor. ",
	"ONLYCANC5USERS":"Your only can create 4 users",
	"SUREDELNUSER":"Are you sure delete this user",
	"EMAILTIP":"Please enter your e-mail verification to complete the registration",
	"PWDTIP":"Consists of 6-16 letters or numbers",
	"REPWDTIP":"Confirm password and password must be consistent",
	"FNAMETIP":"First name can not  be empty",
	"LNAMETIP":"Last name can not  be empty",
	"STANAMETIP":"Plant name can not be empty",
	"CO2RATETIP":"CO2 avoided factor must be numeric",
	"CURRENCYTIP":"Please select the currency unit",
	"INCOMERATETIPTIP":"Yield factor must be numeric",
	"PZINV":"Config Inverter",
	"CKINV":"View Current ShowInverter",
	"BACKINV":"Back To Config Inverter",
	"BACKINVTIP":"You have not choosed the Inverter,Please back to config Inverter.",
	"PZINVOK":"OK",
	"PZINVCANNEL":"Cancel",
	"CHOOSEMONEY":"Please choose the currency unit",
	"CHOOSETIMEZONE":"Please choose the plan timezone",
	"ADDPMU":"Add PMU",
	
	/** 2013-06-21 --PMU SN. To SN. **/
	"PSNO":"SN.",
	"BYNAME":"New alias",
	"OLDBYNAME":"Old alias",
	"ATTR":"Attribute",
	"FACTORY":"Factory",
	"SOFTVRE":"Software version",
	"HARDVRE":"Hardware version",
	"LTIME":"Lastest time",
	"USEDSPACE":"Used space",
	"TOTALSPACE":"Total space",
	"DELETESYSUSER":"Are you sure delete this System administrator",
	"CHART_CHART":"Chart",
	"CHART_IDC":"Idc",
	"CHART_VDC":"Vdc",
	"CHART_ENERGY":"Energy & Power",
	"CHART_FAC":"Fac",
	"CHART_IAC":"Iac",
	"CHART_VAC":"VAC",
	"CHART_TMPE":"Inverter temperature",
	"CHART_GAIN":"Gain",
	"CHART_CO2":"CO2 avoided",
	"CHART_UPDATEUSERINVT":"MModify the default inverter success!",
	"CHART_UPDATEUSERINVT_MAX":"You could not select more than 5 inverters, please re-select",
	"CONF_INPUT_BYNAME":"Please enter an alias!",
	"CONF_INPUT_BYNAME_FORMAT":"Please input legal character!",
	/** 2013-06-21 --PMU SN. To SN. **/
	"CONF_INPUT_PSNO":"Please input SN. ",
	"CONF_INPUT_SERIALNO":"Please input registry key!",
	"CONF_ADDPUM_SUCCESS":"Add success!",
	"CONF_ADDPUM_ERR_NODIFINE":"Add failed: Unknown error!",
	
	/** 2013-06-21 --PMU SN. To SN. **/
	"CONF_ADDPUM_ERR_PSNOERR":"Failed to add: SN. error! ",
	
	/** 2013-06-21 --PMU SN. To SN. **/
	"CONF_ADDPUM_ERR_PSNUSED":"Failed to add: the SN. has been bounded!",
	"CONF_ADDPUM_ERR_NOSTATION":"Add failed: unknown station number or serial number",
	
	/** 2013-06-21 --PMU SN. To SN. **/
	"CONF_INPUT_PSNODEL":"Please input SN.!",
	"CONF_DELPUM_SUCCESS":"Deleted successfully!",
	"CONF_DELPUM_ERR_NODIFINE":"Delete failed: Unknown error!",
	"CONF_SET": "Settings",
	"CONF_DOWNDATA":"Download data",
	"CREATEDT":"Date Created",
	"DEVNAME":"Device name ",
	"FACTORYNAME":"Manufacturer",
	"PENPAI":"Brand",
	"SOFTVER":"Software version ",
	"HARDVER":"Hardware version ",
	"E_TOTAL":"E-Total",
	"E_TOTAL_EX":"E-Total(Initial)",
	"H_TOTAL":"H-Total",
	"DEVMODELNAME":"Type",
	"DEVTYPENAME":"Model",
	"SET_SUCCESS":"Save finished!",
	"SET_FAILD":"Setup failed!",
	"NEED_NUMBER":"Please enter an integer",
	"INPUT_TOOLARGE":"Enter the value is too large",

	"PMU_USEDSPACE":"Storage space",
	"PMU_TOTALSPACE":"The total storage space",
	"PMU_STATE":"Status ",
	"PMU_SOFTVER":"Software version",
	"PMU_HARDWVER":"Hardware version",
	"PMU_LLIP":"Last Login IP",
	"PMU_CURGATE":"Last Login DCGate",
	"PMU_LLDT":"Last login time",
	"RES_DATA_LIST_T":"Time ",
	"RES_DATA_LIST_D":"Date ",
	"RES_DATA_LIST_M":"Month",
	"RES_DATA_LIST_Y":"Year",
	"RES_DATA_LIST":"Numeric table",
	"RES_DATA_LIST_W":"Power",
	"RES_DATA_LIST_ENERGY":"Energy",
	"RES_DATA_LIST_POWER":"Pac",
	"RES_FIND_PWD_MAILSEND":"System verification code sent to your mailbox, please refer to the code to change your password!",
	"RES_FIND_PWD_MAILFAILD_ACC":"Validation code for failure, your account does not exist!",
	"RES_FIND_PWD_CHECKCODE_ERR":"Thevalidation code for failure, please try again or contact your system administrator!",
	"RES_FIND_PWD_INOUT_CHECKCODE":"Please enter the verification code",
	"RES_FIND_PWD_INPUT_NEWPWD":"Please enter new password",
	"RES_FIND_PWD_REPWD":"Please confirm new password",
	"RES_FIND_PWD_TWO_PWD":"The two passwords are inconsistent",
	"RES_FIND_PWD_UPDATE_OK":"Password changed successfully, do you want to return to the login page?",
	"RES_FIND_PWD_ERR_CHECKCODE":"Validation code incorrect!",
	"RES_FIND_PWD_ERR_ACC_NOTFIND":"The account does not exist, faile to modify!",
	"RES_DOWNLOAD_TYPE_TXT":"TXT",
	"RES_DOWNLOAD_TYPE_CSV":"CSV",
	"RES_ACCOUNT":"Account",
	"RES_ACCOUNT_STYLE":"Account format",
	"RES_ADDSHAREACCOUNT":"Add a shared user",
	"RES_ADDSHAREACCOUNT_NEEDINPUT":"Please enter a account to share!",
	"RES_ADDSHAREACCOUNT_ERR_UNKOW":"An unknown error!",
	"RES_ADDSHAREACCOUNT_ERR_NOACC":"The account does not exist!",
	"RES_ADDSHAREACCOUNT_ERR_HAVESHARE":"This account has shared this plant!",
	"RES_DELSHAREACCOUNT_ERR":"Delete Failed!",
	"RES_DELSHAREACCOUNT_CONFIRM":"Are you sure to delete this shared account!",
	"RES_SHAREACCOUNT_UNLOCK_OK":"Unlock success! ",
	"RES_SHAREACCOUNT_UNLOCK_FAILD":"Unlock failed!",
	"RES_SHAREACCOUNT_LOCK_OK":"Lock success! ",
	"RES_SHAREACCOUNT_LOCK_FAILD":"Lock failed!",
	"RES_REPORT_EVENT_DATE_ERR1":"The time to choose is not correct!",
	"RES_REPORT_EVENT_DATE_ERR2":"The time interval is too long, time interval shall not be more than 7 days!",
	"RES_PLANT_JD_ERR1":"Degrees  should be less than 180!",
	"RES_PLANT_JD_ERR2":"Points should be less than 60!",
	"RES_PLANT_JD_ERR3":"Seconds should be less than 60!",
	"RES_PLANT_JD_TOTAL":"Longitude should be less than 180!",
	"RES_PLANT_WD_ERR1":"Degree should be less than 180!",
	"RES_PLANT_WD_ERR2":"Points should be less than 60!",
	"RES_PLANT_WD_ERR3":"Seconds should be less than 60!",
	"RES_PLANT_WD_TOTAL":"Latitude should be less than 180!",
	"RES_POWER_DOWN_DALIY":"Generation capacity",
	"RES_POWER_DOWN_D":"Daily",
	"RES_POWER_DOWN_M":"Monthly",
	"RES_POWER_DOWN_Y":"Yearly",
	"RES_POWER_DOWN_T":"All",
	"RES_CHART_DOWN_ISNO":"SN.",
	"RES_CHART_DOWN_TIME":"Time",
	"RES_CHART_DOWN_TEMP":"TEMP",
	"RES_CHART_DOWN_OBJ_1001":"CO2 avoided-day",
	"RES_CHART_DOWN_OBJ_1002":"CO2 avoided-month",
	"RES_CHART_DOWN_OBJ_1003":"CO2 avoided-year",
	"RES_CHART_DOWN_OBJ_1004":"CO2 avoided-all",
	"RES_CHART_DOWN_OBJ_1101":"Yield-day",
	"RES_CHART_DOWN_OBJ_1102":"Yield-month",
	"RES_CHART_DOWN_OBJ_1103":"Yield-year",
	"RES_CHART_DOWN_OBJ_1104":"Yield-all",
	"RES_CHART_DOWN_OBJ_1201":"Ipv-day",
	"RES_CHART_DOWN_OBJ_1202":"Ipv-7days",
	"RES_CHART_DOWN_OBJ_1301":"Vpv-day",
	"RES_CHART_DOWN_OBJ_1302":"Vpv-7days",
	"RES_CHART_DOWN_OBJ_1401":"Fac-day",
	"RES_CHART_DOWN_OBJ_1402":"Fac-7days",
	"RES_CHART_DOWN_OBJ_1501":"Iac-day",
	"RES_CHART_DOWN_OBJ_1502":"Iac-7days",
	"RES_CHART_DOWN_OBJ_1601":"Vac-day",
	"RES_CHART_DOWN_OBJ_1602":"Vac-7day",
	"RES_CHART_DOWN_OBJ_1701":"Temp-day",
	"RES_CHART_DOWN_OBJ_1702":"Temp-7days",
	"RES_CHART_DOWN_OBJ_1801":"Power-day",
	"RES_CHART_DOWN_OBJ_1802":"Energy-month",
	"RES_CHART_DOWN_OBJ_1803":"Power-year",
	"RES_CHART_DOWN_OBJ_1804":"Energy-all",
	"RES_CHART_DOWN_CO2":"CO2",
	"RES_CHART_DOWN_YIELD":"Yield",
	"RES_CHART_DOWN_POWER":"Power",
	"RES_CHART_DOWN_ENERGY":"Energy",
	"RES_CHANGEPASSWD_INOLDPWD":"Enter the original password",
	"RES_CHANGEPASSWD_INNEWPWD":"Enter new password,length between 6-18",
	
	"RES_CHANGEPASSWD_INCOFMNEWPWD":"Enter the confirm password",
	"RES_CHANGEPASSWD_INCONFMPWDERR":"The two entered passwords do not match!",
	"RES_CHANGEPASSWD_OPT_SUCCESS":"Password changed successfully!",
	"RES_CHANGEPASSWD_OPT_FAILD1":"Password change failed: old password is incorrect!",
	"RES_CHANGEPASSWD_OPT_FAILD2":"Password change failed: account does not exist!",
	"RES_CHANGEPASSWD_OPT_FAILD3":"Password change failed!",
	"RES_WAP_LIKE_ALERT":"WAP access,please use the following address in your mobile phone browser",
	"RES_FIND_PASSWD_NOACC":"Account does not exist or is not activated, the operation failed!",
	"RES_FIND_PASSWD_ERRCODE":"Verification code error!",
	"RES_FIND_PASSWD_IMGNUM":"Enter the picture number",
	"RES_FIND_PASSWD_INCODE":"Please enter the validation code!",
	"RES_FIND_PASSWD_CODENUM":"Verification code must be 4 digits!",
	"RES_CONFIG_REPORT_SEND_OK":"Report is sent successfully! ",
	"RES_CONFIG_REPORT_SEND_ERR":"Fail to send report!",
	"RES_CONFIG_REPORT_SEND_MAIL":"Please enter to receive e-mail address!",
	"RES_CONFIG_REPORT_SEND_MAILEX":"Please input legal E-mail address, seperate with semicolon (;) if more than one E-mail !",
	"RES_CONFIG_REPORT_SAVE_OK":"Saved Successfully!",
	"RES_CONFIG_REPORT_SAVE_ERR":"Fail to save!",
	"RES_CONFIG_REPORT_IN_TIMESPLIT":"Please enter the interval to send!",
	"RES_CONFIG_REPORT_IN_MAXLIMIT_ERR":"The maximum number of events of a single report should between 5 and 1000.",
	"RES_CONFIG_REPORT_IN_NEEDTYPE_ERR":"Select Event Type is required",
	"RES_CONFIG_DEV_INVERTER":"Inverter",
	"RES_CONFIG_DEV_MONITOR":"Monitor",
	"RES_INDEX_ERR_TIME":"Your computer and server time difference too much, some functions may not be available, \n please modify your computer at present time！",
	"RES_REGIST_REMAIL":"Verify that the message has been successfully sent to your mailbox：\n\r",
	"RES_REGIST_MAIL_ERR":"Verification message sending failed!",
	"RES_ACCEPT_SHAREPLAT_OK":"Sharing power station to accept success!",
	"RES_ACCEPT_SHAREPLAT_CONFIRM":"Are you sure you accept the change to share power station?",
	"RES_REFUSE_SHAREPLAT_CONFIRM":"Do you want to cancel this sharing plant?",
	"RES_ACCEPT_SHAREPLAT_ERR1":"Shared power station to accept failure!\n power station ID incorrect!",
	"RES_ACCEPT_SHAREPLAT_ERR2":"Share power station to accept defeat! \n accepting states is not right!",
	"RES_REFUSE_SHAREPLAT_OK":"The shared plant cancel  success!",
	"RES_REFUSE_SHAREPLAT_ERR1":"Shared power station refused to accept defeat! \n power station ID incorrect!",
	"RES_REFUSE_SHAREPLAT_ERR2":"Sharing power station refused to accept defeat! \n to accept the status is not correct!",
	"CONF_DELPUM_ERR_PSNOERR":"Register key or SN. error!",
	"CONF_PUMLIST_SELECTPUM":"Please select the need to set the monitor!",
	"CONF_PUMLIST_UPDATEST_AUTO":"Auto",
	"CONF_PUMLIST_UPDATEST_CLOSE":"Close",
	"CONF_PUMLIST_SETUPDATE_COM":"Are you sure you of selected monitor upgrade?",
	"CONF_PUMLIST_SETUPLOAD_OK":"Set successfully!",
	"Test":"test",
	"CONF_INPUT_LEGAL":"Please input legitimate numbers ！",
	"CONF_DELETE_INV":"Are you sure you want to remove the inverter?",
	"CONF_INPUT_DATE":"Start date can not be greater than the end date!",
	"CONF_ART_OK":"OK",
	"CONF_ART_CANCEL":"Cancel"
} 