var RES = {
		
	"EMAILWRONG":"Forkert e-mail-format",
	"EMAILEXIST":"Test om kontoen er ledig",
	"EMAILHASEXIST":"Kontoen er ikke ledig",
	"EMAILRIGHT":"Kontoen er ledig",
	"PWDLENGTH":"Det indtastede kodeord skal være mindst 6 tegn  ",
	"PWDNOOK":"Password must be alphanumeric",
	"REPWDWRONG":"Det kodeord, du har indtastet to gange, stemmer ikke overens",
	"RES_QUESTION":"Problemfeltet kan ikke være tomt",
	"RES_ANSWER":"Svarfeltet kan ikke være tomt",
	"FIRSTNAMEWORNG":"Navnefeltet kan ikke være tomt",
	"SNAMEWORNG":"Efternavnsfeltet kan ikke være tomt",
	"PASSWORDNOTNULL":"Kodeordsfeltet kan ikke være tomt",
	"REQUESTWRONG":"Forkert forespørgsel",
	"LOGINFALSE":"Forkert e-mail eller kodeord",
	"LOGINFALSE1":"EMAIL du indtastede er forkert",
	"LOGINFALSE2":"The password you entered is incorrect.",
	"LOGINFALSE3":"Retry　time limited!",
	"LOGINFALSE4":"Verification code you entered is incorrect.",
	"BUILDING":"Projektet er under opbygning",
	"INPUTISNO":"Indtast PMU-serienummer",
	"INPUTREGISTCODE":"Indtast registreringskoden",
	"PSNOCANNOTNULL":"PMU-serienummeret kan ikke være tomt",
	"PSNORIGHT":"PMU-serienummeret er ledigt",
	"PMUNOTEXIST":"PMU-serienummeret eksisterer ikke.",
	"PMUHASBINDED":"PMU'en har været bindende",
	"PMUCHECKCODEERR":"Fejl i registreringskode",
	"ONLYNUM":"Der kan kun indtastes tal og decimalpunkter.",
	"CO2XSCANNOTNULL":"Koefficienten for reducering af CO2-emission kan ikke være tom",
	"GAINXSCANNOTNULL":"Koefficienten for indtægt kan ikke være tom",
	"STATIONNAMENOTNULL":"Anlægsnavnet kan ikke være tomt",
	"STARTDTSTYLE":"Format for ibrugtagning (åååå-mm-dd)",
	"STARTDTSTYLEERR":"Format for ibrugtagning (åååå-mm-dd)  ",
	"INSTALLCAPERR":"Installeret kapacitet skal være numerisk",
	"EVENTDELSUC":"Det lykkedes at slette begivenheden.",
	"EVENTDELERROR":"Det lykkedes ikke at slette begivenheder.",
	"STATIONNAMENOTNULL":"Anlægsnavnet kan ikke være tomt",
	"XMUSTNUM":"Længdegrad skal være numerisk",
	"YMUSTNUM":"Breddegrad skal være numerisk",
	"HMUSTNUM":"Indtast højde - skal være numerisk",
	"AZMUSTNUM":"Indtast azimut - skal være et tal  ",
	"AOIMUSTNUM":"Inklinationsvinklen skal være numerisk",
	"AOIMUSTNUM_INSANGLE":"Inklinationsvinkel v?re under 360!",
	"CO2XSMUSTNUM":"af reducering CO2-emission skal være digitalt",
	"GAINXSMUSTNUM":"Indtægten skal være et tal",
	"SNAMENOTNULL":"Anlægsnavnet kan ikke være tomt",
	"SNAMEINPUT":"Indtast anlægsnavn",
	"COUNTRYSELECT":"Vælg venligst et land.",
	"XMUSTINPUT":"Indtast længdegraden",
	"YMUSTINPUT":"Indtast breddegraden.  ",
	"STATESELECT":"Vælg venligst delstat/område",
	"REGNOINPUT":"Registreringskoden skal udfyldes.  ",
	"CITYINPUT":"Indtast en by",
	"CO2XSNOTNULL":"Faktoren for reducering af CO2-emission skal udfyldes  ",
	"GAINXSNOTNULL":"Koefficienten for indtægt kan ikke være tom",
	"SUREDELSTATION":"Er du sikker på, at du vil slette denne station?",
	"SUREDELPMU":"Er du sikker på, at du vil slette denne skærm?",
	"VSPASS":"Verificering godkendt",
	"VSWAIT":"PMU-verificering ikke godkendt; vent venligst.",
	"PMUIDEXWRONG":"Din PMU-LICENSKODE var forkert.",
	"DELSTATIONERR":"Fjern anlægssvigt",
	"DELSTATIONERR_HAVEPMU":"Slet plante mislykkedes: Fjern skærmen.",
	"ONLYCANC5USERS":"Du kan kun oprette 4 brugere",
	"SUREDELNUSER":"Er du sikker på, at du vil fjerne denne bruger?",
	"EMAILTIP":"Indtast din e-mail-verificering for at afslutte registreringen",
	"PWDTIP":"Består af 6-16 tal eller bogstaver",
	"REPWDTIP":"Bekræft kodeord og kodeord skal stemme overens",
	"FNAMETIP":"Navnefeltet kan ikke være tomt",
	"LNAMETIP":"Efternavnsfeltet kan ikke være tomt",
	"STANAMETIP":"Anlægsnavnet kan ikke være tomt",
	"CO2RATETIP":"Faktoren for sparet CO2 skal være numerisk",
	"CURRENCYTIP":"Vælg venligst valutaenheden",
	"INCOMERATETIPTIP":"Udbyttefaktoren skal være numerisk",
	"PZINV":"Konfig inverter",
	"CKINV":"Se strøm Vis inverter",
	"BACKINV":"Tilbage til Konfig inverter",
	"BACKINVTIP":"Du har ikke valgt inverteren; gå tilbage til Konfig inverter.",
	"PZINVOK":"OK",
	"PZINVCANNEL":"Kanal",
	"CHOOSEMONEY":"Vælg venligst møntenhed",
	"CHOOSETIMEZONE":"Vælg venligst stationens tidszone",
	"ADDPMU":"Tilføj PMU",
	
	/** 2013-06-21 --PMU SN. To SN. **/
	"PSNO":"SN.",
	"BYNAME":"Nyt alias",
	"OLDBYNAME":"Gammelt alias",
	"ATTR":"Attribut",
	"FACTORY":"Fabrik",
	"SOFTVRE":"Softwareversion",
	"HARDVRE":"Hardwareversion",
	"LTIME":"Sidste tid",
	"USEDSPACE":"Brugt plads",
	"TOTALSPACE":"Plads i alt",
	"DELETESYSUSER":"Er du sikker på, at du vil slette denne systemadministrator?",
	"CHART_CHART":"Diagram",
	"CHART_IDC":"IDC",
	"CHART_VDC":"VDC",
	"CHART_ENERGY":"Energi og strøm",
	"CHART_FAC":"FAC",
	"CHART_IAC":"IAC",
	"CHART_VAC":"VAC",
	"CHART_TMPE":"Inverter Temperatur",
	"CHART_GAIN":"Udbytte",
	"CHART_CO2":"Reducering af CO2-emission",
	"CHART_UPDATEUSERINVT":"Du har ændret standardinverteren!",
	"CHART_UPDATEUSERINVT_MAX":"Vælg op til fem invertere; vælg igen",
	"CONF_INPUT_BYNAME":"Indtast et alias!",
	"CONF_INPUT_BYNAME_FORMAT":"Please input legal character!",
	"CONF_INPUT_PSNO":"Du skal indtaste monitorens serienummer!",
	"CONF_INPUT_SERIALNO":"Du skal indtaste registreringskoden, hvis du har brug for at tilføje en monitor!  ",
	"CONF_ADDPUM_SUCCESS":"Tilføjelse lykkedes!",
	"CONF_ADDPUM_ERR_NODIFINE":"Tilføjelse lykkedes ikke: Ukendt fejl!",
	"CONF_ADDPUM_ERR_PSNOERR":"Kunne ikke tilføje: fejl i serienummer!  ",
	"CONF_ADDPUM_ERR_PSNUSED":"Kunne ikke tilføje: serienummeret er bundet!  ",
	"CONF_ADDPUM_ERR_NOSTATION":"Tilføjelse lykkedes ikke: ukendt stationsnummer eller serienummer",
	"CONF_INPUT_PSNODEL":"Vær venlig at fjerne monitorens serienummer!  ",
	"CONF_DELPUM_SUCCESS":"Sletning lykkedes!",
	"CONF_DELPUM_ERR_NODIFINE":"Sletning lykkedes ikke: Ukendt fejl!",
	"CONF_SET":"Indstillinger",
	"CONF_DOWNDATA":"Download data",
	"CREATEDT":"Oprettelsesdato",
	"DEVNAME":"Enhedsnavn",
	"FACTORYNAME":"Producent",
	"PENPAI":"Mærke",
	"SOFTVER":"Softwareversion",
	"HARDVER":"Hardwareversion",
	"E_TOTAL":"Samlet genereringskapacitet",
	"E_TOTAL_EX":"E-Total(Initial)",
	"H_TOTAL":"Samlet genereringslængde",
	"DEVMODELNAME":"Type",
	"DEVTYPENAME":"Model",
	"SET_SUCCESS":"Færdig med at gemme!",
	"SET_FAILD":"Opsætning slog fejl!",
	"NEED_NUMBER":"Indtast et helt tal",
	"INPUT_TOOLARGE":"Den indtastede værdi er for høj",

	"PMU_USEDSPACE":"Lagringsplads",
	"PMU_TOTALSPACE":"Samlet lagringsplads",
	"PMU_STATE":"Delstat",
	"PMU_SOFTVER":"Softwareversion",
	"PMU_HARDWVER":"Hardwareversion",
	"PMU_LLIP":"Sidste login-IP",
	"PMU_CURGATE":"Last Login DCGate",
	"PMU_LLDT":"Sidste login-tid",
	"RES_DATA_LIST_T":"Tid",
	"RES_DATA_LIST_D":"Dato",
	"RES_DATA_LIST_M":"Måned",
	"RES_DATA_LIST_Y":"År",
	"RES_DATA_LIST":"Numerisk tabel",
	"RES_DATA_LIST_W":"Strøm",
	"RES_DATA_LIST_ENERGY":"Energi",
	"RES_DATA_LIST_POWER":"PAC",
	"RES_FIND_PWD_MAILSEND":"Systemverificeringskode er sendt til din brevkasse; du henvises til koden til at ændre dit kodeord!",
	"RES_FIND_PWD_MAILFAILD_ACC":"Valideringskode til fejl; din konto eksisterer ikke!",
	"RES_FIND_PWD_CHECKCODE_ERR":"Valideringskoden til fejl; prøv igen eller kontakt din systemadministrator!",
	"RES_FIND_PWD_INOUT_CHECKCODE":"Indtast verificeringskoden",
	"RES_FIND_PWD_INPUT_NEWPWD":"Indtast nyt kodeord",
	"RES_FIND_PWD_REPWD":"Bekræft nyt kodeord",
	"RES_FIND_PWD_TWO_PWD":"De to kodeord stemmer ikke",
	"RES_FIND_PWD_UPDATE_OK":"Det lykkedes at ændre kodeordet; vil du gå tilbage til login-siden",
	"RES_FIND_PWD_ERR_CHECKCODE":"Valideringskoden er forkert; vær venlig at bekræfte verificeringskoden!",
	"RES_FIND_PWD_ERR_ACC_NOTFIND":"Kontoen eksisterer ikke; ændringen lykkedes ikke!",
	"RES_DOWNLOAD_TYPE_TXT":"TXT",
	"RES_DOWNLOAD_TYPE_CSV":"CSV",
	"RES_ACCOUNT":"Konto",
	"RES_ACCOUNT_STYLE":"Kontoformat",
	"RES_ADDSHAREACCOUNT":"Tilføj delt bruger",
	"RES_ADDSHAREACCOUNT_NEEDINPUT":"Indtast en delt konto!",
	"RES_ADDSHAREACCOUNT_ERR_UNKOW":"Ukendt fejl!",
	"RES_ADDSHAREACCOUNT_ERR_NOACC":"Kontoen eksisterer ikke!",
	"RES_ADDSHAREACCOUNT_ERR_HAVESHARE":"Kontoen har en delt konto!",
	"RES_DELSHAREACCOUNT_ERR":"Sletning lykkedes ikke!",
	"RES_DELSHAREACCOUNT_CONFIRM":"Er du sikker på, at du vil slette denne delte konto?",
	"RES_SHAREACCOUNT_UNLOCK_OK":"Det lykkedes at låse op!  ",
	"RES_SHAREACCOUNT_UNLOCK_FAILD":"Det lykkedes ikke at låse op!",
	"RES_SHAREACCOUNT_LOCK_OK":"Det lykkedes at låse!  ",
	"RES_SHAREACCOUNT_LOCK_FAILD":"Det lykkedes ikke at låse!",
	"RES_REPORT_EVENT_DATE_ERR1":"Den valgte tid er forkert!",
	"RES_REPORT_EVENT_DATE_ERR2":"Tidsintervallet er for langt; tidsintervallet må ikke være mere end 7 dage!",
	"RES_PLANT_JD_ERR1":"Grader skal være under 180!",
	"RES_PLANT_JD_ERR2":"Point skal være under 60!",
	"RES_PLANT_JD_ERR3":"Sekunder skal være under 60!",
	"RES_PLANT_JD_TOTAL":"Longitude should be less than 180!",
	"RES_PLANT_WD_ERR1":"Grader skal være under 180!",
	"RES_PLANT_WD_ERR2":"Point skal være under 60!",
	"RES_PLANT_WD_ERR3":"Sekunder skal være under 60!",
	"RES_PLANT_WD_TOTAL":"Latitude should be less than 180!",
	"RES_POWER_DOWN_DALIY":"Genereringskapacitet",
	"RES_POWER_DOWN_D":"Dagligt",
	"RES_POWER_DOWN_M":"Månedligt",
	"RES_POWER_DOWN_Y":"Årligt",
	"RES_POWER_DOWN_T":"Alle",
	"RES_CHART_DOWN_ISNO":"ISNO",
	"RES_CHART_DOWN_TIME":"Tid",
	"RES_CHART_DOWN_TEMP":"Temp",
	"RES_CHART_DOWN_OBJ_1001":"CO2 sparet-dag",
	"RES_CHART_DOWN_OBJ_1002":"CO2 sparet-måned",
	"RES_CHART_DOWN_OBJ_1003":"CO2 sparet-år",
	"RES_CHART_DOWN_OBJ_1004":"CO2 sparet-i alt",
	"RES_CHART_DOWN_OBJ_1101":"Udbytte-dag",
	"RES_CHART_DOWN_OBJ_1102":"Udbytte-måned",
	"RES_CHART_DOWN_OBJ_1103":"Udbytte-år",
	"RES_CHART_DOWN_OBJ_1104":"Udbytte-i alt",
	"RES_CHART_DOWN_OBJ_1201":"Ipv-dag",
	"RES_CHART_DOWN_OBJ_1202":"Ipv-7 dage",
	"RES_CHART_DOWN_OBJ_1301":"Vpv-dag",
	"RES_CHART_DOWN_OBJ_1302":"Vpv-7 dage",
	"RES_CHART_DOWN_OBJ_1401":"Fac-dag",
	"RES_CHART_DOWN_OBJ_1402":"Fac-7 dage",
	"RES_CHART_DOWN_OBJ_1501":"Iac-dag",
	"RES_CHART_DOWN_OBJ_1502":"Iac-7 dage",
	"RES_CHART_DOWN_OBJ_1601":"Vac-dag",
	"RES_CHART_DOWN_OBJ_1602":"Vac-7 dage",
	"RES_CHART_DOWN_OBJ_1701":"Temp-dag",
	"RES_CHART_DOWN_OBJ_1702":"Temp-7 dage",
	"RES_CHART_DOWN_OBJ_1801":"Strøm-dag",
	"RES_CHART_DOWN_OBJ_1802":"Energi-måned",
	"RES_CHART_DOWN_OBJ_1803":"Strøm-år",
	"RES_CHART_DOWN_OBJ_1804":"Energi-i alt",
	"RES_CHART_DOWN_CO2":"CO2",
	"RES_CHART_DOWN_YIELD":"Udbytte",
	"RES_CHART_DOWN_POWER":"Strøm",
	"RES_CHART_DOWN_ENERGY":"Energi",
	"RES_CHANGEPASSWD_INOLDPWD":"Indtast det oprindelige kodeord",
	"RES_CHANGEPASSWD_INNEWPWD":"Indtast nyt kodeord på 6-18 tegn",
	"RES_CHANGEPASSWD_INCOFMNEWPWD":"Bekræft nyt kodeord på 6-18 tegn",
	"RES_CHANGEPASSWD_INCONFMPWDERR":"De to kodeord stemmer ikke overens!",
	"RES_CHANGEPASSWD_OPT_SUCCESS":"Det lykkedes at ændre kodeordet!",
	"RES_CHANGEPASSWD_OPT_FAILD1":"Det lykkedes ikke at ændre kodeordet: det gamle kodeord er forkert!",
	"RES_CHANGEPASSWD_OPT_FAILD2":"Det lykkedes ikke at ændre kodeordet: kontoen eksisterer ikke!",
	"RES_CHANGEPASSWD_OPT_FAILD3":"Det lykkedes ikke at ændre kodeordet!",
	"RES_WAP_LIKE_ALERT":"WAP-adgang, skal du bruge følgende adresse i din mobiltelefon browser",
	"RES_FIND_PASSWD_NOACC":"Konto eksisterer ikke eller er ikke aktiveret, Handlingen mislykkedes!",
	"RES_FIND_PASSWD_ERRCODE":"Bekræft kodefejl!",
	"RES_FIND_PASSWD_IMGNUM":"Indtast det afbildede tal",
	"RES_FIND_PASSWD_INCODE":"Indtast valideringskoden",
	"RES_FIND_PASSWD_CODENUM":"Verificeringskoden skal være 4 tal!",
	"RES_CONFIG_REPORT_SEND_OK":"Rapporten blev sendt!  ",
	"RES_CONFIG_REPORT_SEND_ERR":"Rapporten blev ikke sendt!",
	"RES_CONFIG_REPORT_SEND_MAIL":"Indtast e-mail-adresse for at modtage!",
	"RES_CONFIG_REPORT_SEND_MAILEX":"Please input legal E-mail address, seperate with semicolon (;) if more than one E-mail !",
	"RES_CONFIG_REPORT_SAVE_OK":"Det lykkedes at gemme!",
	"RES_CONFIG_REPORT_SAVE_ERR":"Det lykkedes ikke at gemme!",
	"RES_CONFIG_REPORT_IN_TIMESPLIT":"Indtast afsendingsinterval!",
	"RES_CONFIG_REPORT_IN_MAXLIMIT_ERR":"Maks. antal af begivenheder i en rapport bør være 5-1000",
	"RES_CONFIG_REPORT_IN_NEEDTYPE_ERR":"Du skal vælge mindst én begivenhedstype til at sende",
	"RES_CONFIG_DEV_INVERTER":"Inverter",
	"RES_CONFIG_DEV_MONITOR":"Monitor",
	"RES_INDEX_ERR_TIME":"Your computer and server time difference too much, some functions may not be available, \n please modify your computer at present time！",
	"RES_REGIST_REMAIL":"Verify that the message has been successfully sent to your mailbox：\n\r",
	"RES_REGIST_MAIL_ERR":"Verification message sending failed!",
	"RES_ACCEPT_SHAREPLAT_OK":"Sharing power station to accept success!",
	"RES_ACCEPT_SHAREPLAT_CONFIRM":"Are you sure you accept the change to share power station?",
	"RES_REFUSE_SHAREPLAT_CONFIRM":"Do you want to cancel this sharing plant?",
	"RES_ACCEPT_SHAREPLAT_ERR1":"Shared power station to accept failure!\n power station ID incorrect!",
	"RES_ACCEPT_SHAREPLAT_ERR2":"Share power station to accept defeat! \n accepting states is not right!",
	"RES_REFUSE_SHAREPLAT_OK":"The shared plant cancel  success!",
	"RES_REFUSE_SHAREPLAT_ERR1":"Shared power station refused to accept defeat! \n power station ID incorrect!",
	"RES_REFUSE_SHAREPLAT_ERR2":"Sharing power station refused to accept defeat! \n to accept the status is not correct!",
	"CONF_DELPUM_ERR_PSNOERR":"Licens or SN. error!",
	"CONF_PUMLIST_SELECTPUM":"Please select the need to set the monitor!",
	"CONF_PUMLIST_UPDATEST_AUTO":"Auto",
	"CONF_PUMLIST_UPDATEST_CLOSE":"Close",
	"CONF_PUMLIST_SETUPDATE_COM":"Are you sure you of selected monitor upgrade?",
	"CONF_PUMLIST_SETUPLOAD_OK":"Set successfully!",
	"Test":"test",
	"CONF_INPUT_LEGAL":"Please input legitime numbre ！",
	"CONF_DELETE_INV":"Would you confirm you want to remove the inverter ?\nIt is non-recoverable !",
	"CONF_INPUT_DATE":"Start date can not be greater than the end date!",
	"CONF_ART_OK":"OK",
	"CONF_ART_CANCEL":"Cancel"
		
} 